MangoWeb/Models/CouponDto.cs
namespace MangoWeb.Models
{
    public class CouponDto
    {
        // From the database
        public int CoupionId { get; set; }
        public string CouponCode { get; set; }
        public double DiscountAmount { get; set; }
        public int MinAmount { get; set; }
    }
}

MangoWeb/Models/ErrorViewModel.cs
namespace MangoWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MangoWeb/Models/RequestDto.cs
using static MangoWeb.Utils.SD;

namespace MangoWeb.Models
{
    public class RequestDto
    {
        public ApiType ApiType { get; set; }
        public string Url  { get; set; }
        public object Data { get; set; }

        public string AccessToken { get; set; }
    }
}

MangoWeb/Models/ResponseDto.cs
namespace MangoWeb.Models
{
    public class ResponseDto
    {
        public object Results { get; set; }
        public bool IsSuccess { get; set; } = true;
        public string Message { get; set; } = string.Empty;
    }
}

MangoWeb/Controllers/CouponController.cs
using MangoWeb.Models;
using MangoWeb.Service;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections;
using System.Collections.Generic;

namespace MangoWeb.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }

        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDto> list = new();
            ResponseDto? response = await _couponService.GetAllCoupon();
            if(response!= null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Results));
            }

            return View(list);
        }

        public async Task<IActionResult> CreateCoupon()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCoupon(CouponDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? response = await _couponService.CreateCoupon(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction("CouponIndex");
                }

            }
            return View();
        }

        public async Task<IActionResult> DeleteCoupon(int couponId)
        {
            ResponseDto? response = await _couponService.GetCouponById(couponId);
            if (response != null && response.IsSuccess)
            {
                CouponDto model = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(response.Results));
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCoupon(CouponDto coupon)
        {
            ResponseDto? response = await _couponService.DeleteCoupon(coupon.CoupionId);
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction("CouponIndex");
            }

            return View(coupon);
        }
    }
}

MangoWeb/Controllers/HomeController.cs
using MangoWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MangoWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MangoWeb/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<CouponDto>
<div class="row pb-3">
    <div class="col-6"></div>
    <div class="col-6 text-end">
        <a asp-action="CreateCoupon" class="btn btn-outline-primary">
            <i class="bi bi-plus-square"></i> Create New coupon
        </a>

    </div>
</div>
<table>
    <thead>
        <tr>
            <th>Coupon Code</th>
            <th>Discount Amount</th>
            <th>Minimum Amount</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <td>@item.CouponCode</td>
            <td>@((item.DiscountAmount).ToString("c"))</td>
                <td>@((item.MinAmount).ToString("c"))</td>
            <td>
                <a asp-action="DeleteCoupon" asp-route-couponId="@item.CoupionId" class="btn btn-danger">
                    <i class="bi bi-trash"></i>
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>

MangoWeb/Views/Coupon/CreateCoupon.cshtml
@model CouponDto
<form asp-action="CreateCoupon">
    <br />
    <div class="row">
        <div class="col-2">
            <label class="control-label">Coupon Code</label>
        </div>
        <div class="col-10 pb-3">
            <input class="form-control" asp-for="CouponCode"></input>
            <span asp-validation-for="CouponCode" class="text-danger"></span>
        </div>
        <div class="col-2">
            <label class="control-label">Discount Amount</label>
        </div>
        <div class="col-10 pb-3">
            <input class="form-control" asp-for="DiscountAmount"></input>
            <span asp-validation-for="DiscountAmount" class="text-danger"></span>
        </div>
        <div class="col-2">
            <label class="control-label">Minimum Amount</label>
        </div>
        <div class="col-10 pb-3">
            <input class="form-control" asp-for="MinAmount"></input>
            <span asp-validation-for="MinAmount" class="text-danger"></span>
        </div>
     
    </div>
    <div class="row">
        <div class="col-5 offset-2">
            <a asp-action="CouponIndex" class="btn-primary btn form-control">Back to list</a>
        </div>
        <div class="col-5">
           <input type="submit" value="Create" class="btn btn-success form-control" />
        </div>
    </div>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
}

MangoWeb/Views/Coupon/DeleteCoupon.cshtml
@model CouponDto
<h1>Delete Coupon</h1>
<form asp-action="CreateCoupon">
    <br />
    <input asp-for="CoupionId" hidden/>
    <div class="row">
        <div class="col-2">
            <label class="control-label">Coupon Code</label>
        </div>
        <div class="col-10 pb-3">
            <input class="form-control" asp-for="CouponCode" disabled></input>
            <span asp-validation-for="CouponCode" class="text-danger"></span>
        </div>
        <div class="col-2">
            <label class="control-label">Discount Amount</label>
        </div>
        <div class="col-10 pb-3">
            <input class="form-control" asp-for="DiscountAmount" disabled></input>
            <span asp-validation-for="DiscountAmount" class="text-danger"></span>
        </div>
        <div class="col-2">
            <label class="control-label">Minimum Amount</label>
        </div>
        <div class="col-10 pb-3">
            <input class="form-control" asp-for="MinAmount" disabled></input>
            <span asp-validation-for="MinAmount" class="text-danger"></span>
        </div>

    </div>
    <div class="row">
        <div class="col-5 offset-2">
            <a asp-action="CouponIndex" class="btn-primary btn form-control">Back to list</a>
        </div>
        <div class="col-5">
            <input type="submit" value="Delete Coupon" asp-action="DeleteCoupon" class="btn btn-success form-control" />
        </div>
    </div>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
}

MangoWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MangoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MangoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MangoWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MangoWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2024 made with <i class="bi bi-chat-heart"></i> MangoWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>